name: Daily Telegram Message

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel cron endpoint
        run: |
          curl --fail https://terryanna-bot.vercel.app/api/cron